name: talaa
description: Talaa SuperApp v1.7
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  flutter_stripe: ^10.1.1
flutter:
  uses-material-design: true
